### ISSUE TITLE
Potential Parameter Issues in Evaluation

### ISSUE THREAD

**Issue by Jasmine-ycj** [paulhager/MMCL-Tabular-Imaging#20] opened 2024-07-19 14:28 UTC
Hi Hager,

Thank you for sharing your work. I have been going through your code and found it extremely insightful. 

However, I came across a few lines that I thought might need some adjustments. Could you please take a look and confirm if these changes are indeed necessary?

1. **`Evaluator.py` lines 17-22**: The code uses `hparams.datatype` to select the evaluating model based on the modality.  Should it instead be `hparams.eval_datatype`? These two parameters seem to have different meanings.

2. **`evaluate.py` lines 56-59**: The `hparams.weights` is being used, but I noticed that the `config.yaml` file only contains a parameter named `weighted_sampler`. Is it possible that `hparams.weights` should be changed to `weighted_sampler`? 

Thank you.

**Comment by paulhager** [comment] 2024-07-19 15:09
Hi Jasmine,

Thanks for the kind words, I'm glad the code is of use to you.

1. You could specify eval_datatype here if you want to train multimodal and then immediately eval tabular or with imaging_and_tabular. I changed it back to just datatype to simplify my configs and make it easier to train from checkpoints. The code works as intended but feel free to change it if the flexibility suits you better. You can also delete eval_datatype from the config if you are fine with the current functionality.
2. That is correct, good catch. Pushed a fix.

**Closed by paulhager** 2024-07-19 15:09 UTC
